name: workout
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.7.2+3
  device_info_plus: ^9.0.3
  provider: ^6.0.5
  firebase_remote_config: ^4.2.5
  firebase_analytics: ^10.4.5
  shared_preferences: ^2.2.0
  firebase_core: ^2.15.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/mock_data/gif/
    - assets/mock_data/data.json
    - icon/icon.png
